server:
  port: 8080


spring:
  application:
    name: product-service


  #database Configuration (H2 In-Memory)
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: root                   # Default username
    password: root                   # Default password is empty
    driver-class-name: com.mysql.cj.jdbc.Driver


  #JPA / Hibernate settings
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update                   # Automatically creates tables based on your Entity classes
      show-sql: true                     # Prints the SQL queries in the console

  #H2 Console (A web page to view the database)

#  h2:
#    console:
#      enabled: true
#      path: /h2-console